### ISSUE TITLE
Complex transformations

### ISSUE THREAD

**Issue by avanderhoorn** [HeyImAlex/reselect-map#1]
I currently have a reducer which looks something like the following:
```
const initialState = { 
    listing: [],
    byId: {},
    byContextId: {},
    filteredIds: [],
    filters: {},
    selectedContextId: null,
    selectedContext: null
}

export default function messages(state = initialState, action) {
    if (action.type == MESSAGES_RECEIVED_BATCH || action.type == MESSAGES_RECEIVED_ITEM) { 
        console.time(`[PERF] ${MESSAGES_RECEIVED_BATCH}`);

        let listing = state.listing;
        let byId = state.byId;
        let byContextId = state.byContextId;
 
        // sometimes I can get messages sent which I already have
        const newListing = [];
        action.messages.forEach(message => {
            if (!state.byId[message.id]) {
                newListing.push(message);
            }
        });

        if (newListing.length > 0) {
            // - index messages by id
            // - group messages by context id (with nested list and sub grouping by type)
            // - store messages in array

            let newById = {};
            let newByContextId = {};
            newListing.forEach(message => {
                const context = newByContextId[message.context.id] || { listing: [], byType: {} };
                message.types.forEach(type => {
                    context.byType[type] = context.byType[type] || [];
                    context.byType[type].push(message);
                });
                context.listing.push(message);

                newByContextId[message.context.id] = context;
                newById[message.id] = message;
            });
            for (var contextId in byContextId) {
                const context = byContextId[contextId];
                const newContext = newByContextId[contextId];
                if (newContext) {
                    newContext.listing.push(...context.listing);
                    Object.assign(newContext.byType, context.byType);
                }
                else {
                    newByContextId[contextId] = context;
                }
            }
            byContextId = newByContextId;
            byId = Object.assign(newById, state.byId);

            newListing.push(listing);
            listing = newListing;

        }

        ....

        console.timeEnd(`[PERF] ${MESSAGES_RECEIVED_BATCH}`);

        return {
            ...state,
            listing,
            byId,
            byContextId,
            filteredIds,
            selectedContext
        };
    }
    else if (action.type == MESSAGES_REQUESTED_ITEM) {
        return {
            ...state,
            selectedContextId: action.contextId,
            selectedContext: state.byContextId[action.contextId]
        }
    }
    return state;
}
```

To help paint a picture of what the above is doing, the following is the type of data I have and the structures that I'm trying to have "access" to (note, it's more complex than this but trying to simply things):
```
// input
action.messages = [
    { id: 1, context: { id: 1, ... }, types: [ 'a', 'b' ], payload: { ... } }, 
    { id: 2, context: { id: 2, ... }, types: [ 'c' ], payload: { ... } }, 
    { id: 3, context: { id: 1, ... }, types: [ 'a' ], payload: { ... } }, 
    { id: 4, context: { id: 1, ... }, types: [ 'c' ], payload: { ... } }, 
    { id: 5, context: { id: 1, ... }, types: [ 'd' ], payload: { ... } }, 
    { id: 6, context: { id: 2, ... }, types: [ 'c' ], payload: { ... } }, 
    { id: 7, context: { id: 2, ... }, types: [ 'a' ], payload: { ... } }, 
];

// output
state = {
    listing: [ ... ], // Simple: Unique list of messages by message.id
    byId: { ... },   // Simple: Indexed messages by message.id
    byContextId: {
        1: {
            listing: [ ... ], // Unique list of messages by message.id where context.id = 1
            byType: {
                'a': [ .... ], // Unique list of messages by message.id where message.context.id = 1 and message.type = 'a'
                'b': [ .... ], // Unique list of messages by message.id where message.context.id = 1 and message.type = 'b'
                ...
            },
            ... // others here
        }
    }, // Harder: Grouped by message.context.id
    ...
}
```

As you can see there are some complex but not extraordinary stuff going on here. There is also a lot which shouldn't be here and should be in selector. 

Now, given the relative complexity of the transformation and number of messages that are being dealt with (range 500-5000), I'm keen not to have to recalculate everything each time I get a new message come in (which I'm currently defending against and selectors don't do out of the box). In thinking about shifting this logic into selectors, I'm trying to figure out how I'm best to only recalculate what has actually been affected... hence how I came across `reselect-map`.

When looking at the API I'm left wondering if there is currently support for my needs? What I'm thinking I need is a way to describe how the data should be "keyed"... In my case I would say that the key for `byContextId` is at `message.context.id`... then `reselect-map` would only make me recalculate the state for the contextIds that where received in received batch of messages and remember the state of the rest.

Any thoughts on how I should do this or I'm thinking about this incorrectly, etc.

**Comment by avanderhoorn** [comment]
// @ellbee @gaearon

**Comment by HeyImAlex** [comment]
You're wanting aggregates like group-by, but unfortunately this package really only does simple 1-1 transformation. Writing a similar package for grouping and filtering might be possible, but I don't think I wanna.

Anyways using it would look almost exactly like what you have now, except with a step before you start grouping where you would diff the next listings with the previous ones. A nicer api could be made that would reduce a lot of the boilerplate, but it wouldn't garner you any performance improvements.

**Comment by avanderhoorn** [comment]
Thanks for the response. Part of the general problem here though, is that one doesn't have access to the previous state/result of the selector... so trying to optimize things based on the difference is really difficult.

**Comment by avanderhoorn** [comment]
Once you have the previous state, you could assert that the next thing you need is knowing what changed from the last run to this run.

**Comment by HeyImAlex** [comment]
Yeah, you're pretty much left to write a memoizing function for yourself. Maybe reselect could be changed to be more react-like in that it exposes caching details to the user.

In any case, it's not that difficult to do on your own.

```javascript
const mySelector = (() => {
  let lastListing = null;
  let lastResult = null;
  return (state) => {
    if (lastListing === null) {
      // compute everything from scratch
      lastResult = result
      return result
    } else if (state.listing === lastListing) {
      return lastResult
    }
    // diff the listings
    // do what you do now
    lastResult = result
    return result
  }
})();
```

**Comment by avanderhoorn** [comment]
As a first step to support this, the `defaultMemoize` in reselect could be updated to pass the `lastResult` into the selector callback that gets executed... this works (as I've made the change and it generally works), but you still need to know what the delta on the input is. Hence that lead me to also passing in the `lastArgs` which leads to something that looks like the following:
```
  test('first argument can be an array', () => { 
    const selector = createSelector(
      [ state => state.a, state => state.b ],
      (a, b, _a, _b, previous) => { 
          console.log('RUN...')
          console.log('current a', a);
          console.log('previous _a', _a);
          console.log('current b', b);
          console.log('previous _b', _b);
          console.log('previous result', previous);
        return { c: a + b }
      }
    )
  })

//OUTPUT
RUN...
a 1
_a undefined
b 2
_b undefined
undefined

RUN...
a 3
_a 1
b 2
_b 2
{ c: 3 }
```

I realize that this isn't exactly the problem that `reselect-map` is trying to solve, but its in a area/problem space.

**Comment by ms88privat** [comment]
@avanderhoorn I did not dive deep into your example, but I never saw a reducer like this. Maybe normalising your Messages will help (splitting context out of it?). Do you know this [library](https://github.com/paularmstrong/normalizr)?

**Comment by HeyImAlex** [comment]
I mean, if you ***really*** do not want to write a full memoization function...

```javascript
export default function exposedMem(fn, shouldUpdate = defaultShouldUpdate) {
  let lastArgs = null;
  let lastResult = null;
  return (...args) => {
    if (shouldUpdate(lastArgs, args)) {
      lastResult = fn(...args);
      lastArgs = args;
    }
    return lastResult;
  }
}

function defaultShouldUpdate(args, lastArgs) {
  return (
    lastArgs !== null &&
    lastArgs.length === args.length &&
    args.every((value, index) => value === lastArgs[index])
  );
}
```
