### ISSUE TITLE
Customizing key used for memoization

### ISSUE THREAD

**Issue by jedwards1211** [heyimalex/reselect-map#11]
~~The array/list selectors in this package have a problem: if you splice in some elements at index `n`, you lose all the memoization for everything that came after `n`.~~

Edit: now that I glanced at the code I see you have an optional undocumented `equalityCheck` argument.  In a lot of cases it's probably more straightforward to just use a function that determines the cache key for a given element.

But often it's common to have an array of objects containing a property that can act as a key:
```js
[
  {id: 1, name: 'Andy'},
  {id: 2, name: 'John'},
  {id: 3, name: 'Martha'},
  ...
]
```

In this case if I could just provide a function that tells `createArraySelector` to use `element.id` as the key, then the results for each `id` would stay memoized no matter how the array was shuffled.

One way to do this would be to provide a `keyBy` option with the signature `(value, originalKey) => newKey`:
```js
createArraySelector(
  state => state.users,
  state => state.multiplier,
  (user, multiplier) => user.age * multiplier,
  {keyBy: user => user.id}
)
```

**Comment by jedwards1211** [comment]
Yeah that's a good point.

I came to this library from code I had written to manually instantiate and apply a rather complex selector to each value in an array, and I get some benefit from applying the previous selector for a given key if the value for that key changed but none of its contents relevant to the selector changed (assuming a way to create a custom selector for each key were provided by this library).

However, after converting that selector to an unmemoized function and using it with `reselect-map`, I don't seem to have any performance problems, so it's debatable whether it's worth the extra complexity in most cases.

**Comment by heyimalex** [comment]
Yeah, composition with caching is hard in general. I'll leave this issue open in case anyone else is interested in a similar thing, but probably won't move forward since the current code handles the common case well enough.

**Comment by heyimalex** [comment]
Actually I like zero open issues ahahahahahahahahahahahaha
