### ISSUE TITLE
Is there any way to customize the equalityCheck?

### ISSUE THREAD

**Issue by W1U02** [heyimalex/reselect-map#16]
memorize functions have a equalityCheck parameter but there is no way to set the equalityCheck function.

And `createMappedSelectorCreator` is not exported too.

**Comment by heyimalex** [comment]
There are new functions in v1.0.5 which allow you to pass in a custom equality check function! They're not documented in the readme, but you can see them [here](https://github.com/heyimalex/reselect-map/blob/c15a52e4ebe94b78642a014631d55f343f35f3e7/src/index.js#L75).
